use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use svgtypes::{PathParser, PathSegment};

fn main() {
    println!("cargo:rerun-if-changed=selected.toml");
    println!("cargo:rerun-if-changed=source");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let selected = parse_selection(&manifest_dir.join("selected.toml"));
    let generated = generate(&manifest_dir, &selected);
    let output = PathBuf::from(env::var("OUT_DIR").expect("Cargo output directory"));
    fs::write(output.join("generated.rs"), generated).expect("write generated Tabler icon data");
}

fn parse_selection(path: &Path) -> Vec<(String, String)> {
    let source = fs::read_to_string(path).expect("read selected.toml");
    source
        .lines()
        .filter_map(|line| {
            let line = line.split('#').next()?.trim();
            if line.is_empty() {
                return None;
            }
            let (variant, file_name) = line.split_once('=')?;
            Some((
                variant.trim().to_owned(),
                file_name.trim().trim_matches('"').to_owned(),
            ))
        })
        .collect()
}

fn generate(manifest_dir: &Path, selected: &[(String, String)]) -> String {
    let mut output = String::from(
        "// Generated by build.rs from selected Tabler SVG files.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         pub enum Icon {\n",
    );
    for (variant, file_name) in selected {
        output.push_str(&format!("    /// Tabler `{file_name}` icon.\n"));
        output.push_str(&format!("    {variant},\n"));
    }
    output.push_str("}\n\n");
    output.push_str(
        "/// Every Tabler icon selected for the Scarlet UI standard vocabulary.\n\
         pub const ALL_ICONS: &[Icon] = &[\n",
    );
    for (variant, _) in selected {
        output.push_str(&format!("    Icon::{variant},\n"));
    }
    output.push_str(" ];\n\n");
    output.push_str(
        "impl Icon {\n\
         /// Return the upstream Tabler icon file name.\n\
         ///\n\
         /// # Returns\n\
         ///\n\
         /// Stable kebab-case icon name.\n\
         pub const fn name(self) -> &'static str {\n\
             match self {\n",
    );
    for (variant, file_name) in selected {
        output.push_str(&format!("        Icon::{variant} => \"{file_name}\",\n"));
    }
    output.push_str(
        "        }\n\
         \x20   }\n\
         \n\
         \x20   /// Return whether the upstream set provides a filled variant.\n\
         \x20   ///\n\
         \x20   /// # Returns\n\
         \x20   ///\n\
         \x20   /// `true` when official Tabler filled vector data is available.\n\
         \x20   pub const fn has_filled(self) -> bool {\n\
         \x20       match self {\n",
    );
    for (variant, file_name) in selected {
        let has_filled = manifest_dir
            .join("source")
            .join("filled")
            .join(format!("{file_name}.svg"))
            .exists();
        output.push_str(&format!("        Icon::{variant} => {has_filled},\n"));
    }
    output.push_str("        }\n    }\n}\n\n");

    for (variant, file_name) in selected {
        let base = constant_name(variant);
        let outline_path = manifest_dir
            .join("source")
            .join("outline")
            .join(format!("{file_name}.svg"));
        write_icon_commands(&mut output, &format!("{base}_OUTLINE"), &outline_path);

        let filled_path = manifest_dir
            .join("source")
            .join("filled")
            .join(format!("{file_name}.svg"));
        if filled_path.exists() {
            write_icon_commands(&mut output, &format!("{base}_FILLED"), &filled_path);
        }
    }

    output.push_str(
        "/// Return generated vector commands for an icon.\n\
         ///\n\
         /// # Arguments\n\
         ///\n\
         /// * `icon` - Selected Tabler icon.\n\
         ///\n\
         /// # Returns\n\
         ///\n\
         /// Commands in Tabler's 24×24 coordinate system.\n\
         pub fn icon_commands(icon: Icon) -> &'static [IconCommand] {\n\
             match icon {\n",
    );
    for (variant, _) in selected {
        output.push_str(&format!(
            "        Icon::{variant} => {}_OUTLINE,\n",
            constant_name(variant)
        ));
    }
    output.push_str("    }\n}\n\n");
    output.push_str(
        "/// Return official filled vector commands for an icon when available.\n\
         ///\n\
         /// # Arguments\n\
         ///\n\
         /// * `icon` - Selected Tabler icon.\n\
         ///\n\
         /// # Returns\n\
         ///\n\
         /// Filled commands in Tabler's 24×24 coordinate system, or `None`\n\
         /// when Tabler does not publish a filled variant.\n\
         pub fn filled_icon_commands(icon: Icon) -> Option<&'static [IconCommand]> {\n\
         \x20   match icon {\n",
    );
    for (variant, file_name) in selected {
        let filled_path = manifest_dir
            .join("source")
            .join("filled")
            .join(format!("{file_name}.svg"));
        if filled_path.exists() {
            output.push_str(&format!(
                "        Icon::{variant} => Some({}_FILLED),\n",
                constant_name(variant)
            ));
        } else {
            output.push_str(&format!("        Icon::{variant} => None,\n"));
        }
    }
    output.push_str("    }\n}\n");
    output
}

fn write_icon_commands(output: &mut String, constant: &str, svg_path: &Path) {
    let svg = fs::read_to_string(svg_path)
        .unwrap_or_else(|error| panic!("read {}: {error}", svg_path.display()));
    let path_data = svg_path_data(&svg);
    output.push_str(&format!("const {constant}: &[IconCommand] = &[\n"));
    for data in path_data {
        let segments = PathParser::from(data.as_str()).map(|segment| {
            segment.unwrap_or_else(|error| panic!("parse path in {}: {error}", svg_path.display()))
        });
        for command in normalize(segments) {
            output.push_str("    ");
            output.push_str(&command.source());
            output.push_str(",\n");
        }
        output.push_str("    IconCommand::EndPath,\n");
    }
    output.push_str("];\n\n");
}

fn constant_name(variant: &str) -> String {
    let mut output = String::from("ICON_");
    for (index, character) in variant.chars().enumerate() {
        if index > 0 && character.is_ascii_uppercase() {
            output.push('_');
        }
        output.push(character.to_ascii_uppercase());
    }
    output
}

fn svg_path_data(svg: &str) -> Vec<String> {
    let mut paths = Vec::new();
    let mut rest = svg;
    while let Some(start) = rest.find("<path") {
        rest = &rest[start + 5..];
        let end = rest.find('>').expect("terminated path element");
        let element = &rest[..end];
        if let Some(attribute) = element.find("d=\"") {
            let value = &element[attribute + 3..];
            let value_end = value.find('"').expect("terminated path data");
            paths.push(value[..value_end].to_owned());
        }
        rest = &rest[end + 1..];
    }
    assert!(!paths.is_empty(), "SVG contains no path data");
    paths
}

#[derive(Clone, Copy)]
enum Command {
    Move(f64, f64),
    Line(f64, f64),
    Quad(f64, f64, f64, f64),
    Cubic(f64, f64, f64, f64, f64, f64),
    Arc(f64, f64, f64, bool, bool, f64, f64),
    Close,
}

impl Command {
    fn source(self) -> String {
        match self {
            Self::Move(x, y) => {
                format!("IconCommand::MoveTo({}f32, {}f32)", number(x), number(y))
            }
            Self::Line(x, y) => {
                format!("IconCommand::LineTo({}f32, {}f32)", number(x), number(y))
            }
            Self::Cubic(x1, y1, x2, y2, x, y) => {
                format!(
                    "IconCommand::CubicTo {{ control_1_x: {}f32, control_1_y: {}f32, control_2_x: {}f32, control_2_y: {}f32, x: {}f32, y: {}f32 }}",
                    number(x1),
                    number(y1),
                    number(x2),
                    number(y2),
                    number(x),
                    number(y)
                )
            }
            Self::Quad(x1, y1, x, y) => {
                format!(
                    "IconCommand::QuadTo {{ control_x: {}f32, control_y: {}f32, x: {}f32, y: {}f32 }}",
                    number(x1),
                    number(y1),
                    number(x),
                    number(y)
                )
            }
            Self::Arc(rx, ry, rotation, large_arc, sweep, x, y) => {
                format!(
                    "IconCommand::ArcTo {{ radius_x: {}f32, radius_y: {}f32, rotation: {}f32, large_arc: {large_arc}, sweep: {sweep}, x: {}f32, y: {}f32 }}",
                    number(rx),
                    number(ry),
                    number(rotation),
                    number(x),
                    number(y)
                )
            }
            Self::Close => String::from("IconCommand::Close"),
        }
    }
}

fn normalize(segments: impl Iterator<Item = PathSegment>) -> Vec<Command> {
    let mut commands = Vec::new();
    let mut current = (0.0, 0.0);
    let mut subpath_start = current;
    let mut cubic_control = None;
    let mut quadratic_control = None;

    for segment in segments {
        let endpoint = |abs: bool, x: f64, y: f64, current: (f64, f64)| {
            if abs {
                (x, y)
            } else {
                (current.0 + x, current.1 + y)
            }
        };
        match segment {
            PathSegment::MoveTo { abs, x, y } => {
                current = endpoint(abs, x, y, current);
                subpath_start = current;
                commands.push(Command::Move(current.0, current.1));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::LineTo { abs, x, y } => {
                current = endpoint(abs, x, y, current);
                commands.push(Command::Line(current.0, current.1));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::HorizontalLineTo { abs, x } => {
                current.0 = if abs { x } else { current.0 + x };
                commands.push(Command::Line(current.0, current.1));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::VerticalLineTo { abs, y } => {
                current.1 = if abs { y } else { current.1 + y };
                commands.push(Command::Line(current.0, current.1));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::CurveTo {
                abs,
                x1,
                y1,
                x2,
                y2,
                x,
                y,
            } => {
                let control_1 = endpoint(abs, x1, y1, current);
                let control_2 = endpoint(abs, x2, y2, current);
                current = endpoint(abs, x, y, current);
                commands.push(Command::Cubic(
                    control_1.0,
                    control_1.1,
                    control_2.0,
                    control_2.1,
                    current.0,
                    current.1,
                ));
                cubic_control = Some(control_2);
                quadratic_control = None;
            }
            PathSegment::SmoothCurveTo { abs, x2, y2, x, y } => {
                let control_1 = cubic_control
                    .map(|control: (f64, f64)| {
                        (current.0 * 2.0 - control.0, current.1 * 2.0 - control.1)
                    })
                    .unwrap_or(current);
                let control_2 = endpoint(abs, x2, y2, current);
                current = endpoint(abs, x, y, current);
                commands.push(Command::Cubic(
                    control_1.0,
                    control_1.1,
                    control_2.0,
                    control_2.1,
                    current.0,
                    current.1,
                ));
                cubic_control = Some(control_2);
                quadratic_control = None;
            }
            PathSegment::Quadratic { abs, x1, y1, x, y } => {
                let control = endpoint(abs, x1, y1, current);
                current = endpoint(abs, x, y, current);
                commands.push(Command::Quad(control.0, control.1, current.0, current.1));
                quadratic_control = Some(control);
                cubic_control = None;
            }
            PathSegment::SmoothQuadratic { abs, x, y } => {
                let control = quadratic_control
                    .map(|control: (f64, f64)| {
                        (current.0 * 2.0 - control.0, current.1 * 2.0 - control.1)
                    })
                    .unwrap_or(current);
                current = endpoint(abs, x, y, current);
                commands.push(Command::Quad(control.0, control.1, current.0, current.1));
                quadratic_control = Some(control);
                cubic_control = None;
            }
            PathSegment::EllipticalArc {
                abs,
                rx,
                ry,
                x_axis_rotation,
                large_arc,
                sweep,
                x,
                y,
            } => {
                current = endpoint(abs, x, y, current);
                commands.push(Command::Arc(
                    rx,
                    ry,
                    x_axis_rotation,
                    large_arc,
                    sweep,
                    current.0,
                    current.1,
                ));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::ClosePath { .. } => {
                current = subpath_start;
                commands.push(Command::Close);
                cubic_control = None;
                quadratic_control = None;
            }
        }
    }
    commands
}

fn number(value: f64) -> String {
    if value == 0.0 {
        String::from("0.0")
    } else {
        format!("{value:?}")
    }
}
