[package]
name = "scarlet-ui-platform-sws"
version = "1.0.0"
edition = "2024"

[features]
default = ["std"]
legacy-scarlet-std = [
    "scarlet-ui-core/legacy-scarlet-std",
    "scarlet-ui-renderer-sgfx/legacy-scarlet-std",
    "dep:scarlet-std",
    "sgfx/legacy-scarlet-std",
    "sws-client/legacy-scarlet-std",
    "sws-protocol/legacy-scarlet-std",
]
std = [
    "scarlet-ui-core/std",
    "scarlet-ui-renderer-sgfx/std",
    "sgfx/std",
    "sws-client/std",
    "sws-protocol/std",
]

[dependencies]
scarlet-ui-core = { path = "../scarlet-ui-core", default-features = false }
scarlet-ui-renderer-sgfx = { path = "../scarlet-ui-renderer-sgfx", default-features = false }

[target.'cfg(target_os = "scarlet")'.dependencies]
scarlet-std = { git = "https://github.com/petitstrawberry/Scarlet", rev = "85f0cead4cb4c9add021360f1b469f08bf0d23a9", package = "scarlet-std", optional = true }
sgfx = { git = "https://github.com/petitstrawberry/sgfx", rev = "8f2f7cd626c6f391516d2c5c5510b71db5cf4bf7", package = "sgfx", default-features = false, features = ["std", "backend-scarlet-virgl", "backend-scarlet-adreno"] }
sws-client = { git = "https://github.com/petitstrawberry/Scarlet", rev = "85f0cead4cb4c9add021360f1b469f08bf0d23a9", package = "sws-client", default-features = false }
sws-protocol = { git = "https://github.com/petitstrawberry/Scarlet", rev = "85f0cead4cb4c9add021360f1b469f08bf0d23a9", package = "sws-protocol", default-features = false }

[lib]
name = "scarlet_ui_platform_sws"
path = "src/lib.rs"
