[package]
name = "scarlet-ui-platform-sws"
version = "1.0.0"
edition = "2024"

[features]
default = ["std"]
legacy-scarlet-std = [
    "scarlet-ui-core/legacy-scarlet-std",
    "scarlet-ui-renderer-sgfx/legacy-scarlet-std",
    "dep:scarlet-std",
    "sgfx/legacy-scarlet-std",
    "sws-client/legacy-scarlet-std",
    "sws-protocol/legacy-scarlet-std",
]
std = [
    "scarlet-ui-core/std",
    "scarlet-ui-renderer-sgfx/std",
    "sgfx/std",
    "sws-client/std",
    "sws-protocol/std",
]

[dependencies]
scarlet-ui-core = { path = "../scarlet-ui-core", default-features = false }
scarlet-ui-renderer-sgfx = { path = "../scarlet-ui-renderer-sgfx", default-features = false }

[target.'cfg(target_os = "scarlet")'.dependencies]
scarlet-std = { git = "https://github.com/petitstrawberry/Scarlet", rev = "4ea47edf7e37f50f3c286e2fe51c784f6d282cfe", package = "scarlet-std", optional = true }
sgfx = { git = "https://github.com/petitstrawberry/sgfx", rev = "ddf00563c617a30bbf64fa5dbe8152c852d493f9", package = "sgfx", default-features = false, features = ["backend-scarlet-virgl", "backend-scarlet-adreno", "backend-scarlet-maxwell"] }
sws-client = { git = "https://github.com/petitstrawberry/Scarlet", rev = "4ea47edf7e37f50f3c286e2fe51c784f6d282cfe", package = "sws-client", default-features = false }
sws-protocol = { git = "https://github.com/petitstrawberry/Scarlet", rev = "4ea47edf7e37f50f3c286e2fe51c784f6d282cfe", package = "sws-protocol", default-features = false }

[lib]
name = "scarlet_ui_platform_sws"
path = "src/lib.rs"
