use std::collections::BTreeMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};

use lyon_path::Path as LyonPath;
use lyon_tessellation::{
    BuffersBuilder, FillOptions, FillTessellator, FillVertex, StrokeOptions, StrokeTessellator,
    StrokeVertex, VertexBuffers,
};
use svgtypes::{PathParser, PathSegment};

#[derive(Clone, Copy)]
struct Triangle {
    a: [f32; 2],
    b: [f32; 2],
    c: [f32; 2],
    color: u32,
}

#[derive(Clone, Copy)]
enum Command {
    Move(f64, f64),
    Line(f64, f64),
    Quad(f64, f64, f64, f64),
    Cubic(f64, f64, f64, f64, f64, f64),
    Close,
}

fn main() {
    println!("cargo:rerun-if-changed=source");

    let manifest_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest directory"));
    let mut assets = Vec::new();
    assets.extend(read_assets(&manifest_dir.join("source/extra"), "Extra"));
    assets.extend(read_assets(&manifest_dir.join("source/vivid"), "Vivid"));
    assets.sort_by(|left, right| left.variant.cmp(&right.variant));

    let mut generated = String::from(
        "// Generated by build.rs from file-icon-vectors SVG files.\n\
         #[derive(Clone, Copy, Debug, PartialEq, Eq, PartialOrd, Ord, Hash)]\n\
         pub enum FileIcon {\n",
    );
    for asset in &assets {
        generated.push_str(&format!("    /// `{}` file icon.\n", asset.name));
        generated.push_str(&format!("    {},\n", asset.variant));
    }
    generated.push_str("}\n\n");

    for asset in &assets {
        generated.push_str(&format!(
            "const {}: &[FileIconTriangle] = &[\n",
            asset.constant
        ));
        for triangle in &asset.triangles {
            generated.push_str(&format!(
                "    FileIconTriangle {{ a: [{:?}f32, {:?}f32], b: [{:?}f32, {:?}f32], c: [{:?}f32, {:?}f32], color: 0x{:08x} }},\n",
                triangle.a[0],
                triangle.a[1],
                triangle.b[0],
                triangle.b[1],
                triangle.c[0],
                triangle.c[1],
                triangle.color
            ));
        }
        generated.push_str("];\n\n");
    }

    generated.push_str(
        "/// Return embedded vector data for a file icon.\n\
         ///\n\
         /// # Arguments\n\
         ///\n\
         /// * `icon` - Embedded file icon identifier.\n\
         ///\n\
         /// # Returns\n\
         ///\n\
         /// The icon's source dimensions and colored triangle mesh.\n\
         pub const fn file_icon_data(icon: FileIcon) -> &'static FileIconData {\n\
         \x20   match icon {\n",
    );
    for asset in &assets {
        generated.push_str(&format!(
            "        FileIcon::{} => &FileIconData {{ width: {:?}f32, height: {:?}f32, triangles: {} }},\n",
            asset.variant, asset.width, asset.height, asset.constant
        ));
    }
    generated.push_str("    }\n}\n\n");

    generated.push_str(
        "/// Find a Vivid icon by a lowercase file extension.\n\
         ///\n\
         /// # Arguments\n\
         ///\n\
         /// * `extension` - Extension without the leading dot.\n\
         ///\n\
         /// # Returns\n\
         ///\n\
         /// The matching Vivid icon, or `None` for an unknown extension.\n\
         pub fn vivid_icon_for_extension(extension: &str) -> Option<FileIcon> {\n\
         \x20   match extension {\n",
    );
    for asset in assets.iter().filter(|asset| asset.set == "Vivid") {
        generated.push_str(&format!(
            "        {:?} => Some(FileIcon::{}),\n",
            asset.name, asset.variant
        ));
    }
    generated.push_str("        _ => None,\n    }\n}\n\n");

    generated.push_str(
        "/// Return the standard Extra folder icon.\n\
         ///\n\
         /// # Returns\n\
         ///\n\
         /// The colored closed folder artwork.\n\
         pub const fn extra_folder_icon() -> FileIcon {\n\
         \x20   FileIcon::ExtraFolder\n\
         }\n\
         \n\
         /// Return the standard Extra open-folder icon.\n\
         ///\n\
         /// # Returns\n\
         ///\n\
         /// The colored open folder artwork.\n\
         pub const fn extra_open_folder_icon() -> FileIcon {\n\
         \x20   FileIcon::ExtraFolderOpen\n\
         }\n",
    );

    let output = PathBuf::from(env::var("OUT_DIR").expect("Cargo output directory"));
    fs::write(output.join("generated.rs"), generated).expect("write generated file icon data");
}

struct Asset {
    set: String,
    name: String,
    variant: String,
    constant: String,
    width: f64,
    height: f64,
    triangles: Vec<Triangle>,
}

fn read_assets(directory: &Path, set: &str) -> Vec<Asset> {
    let mut assets = Vec::new();
    for entry in fs::read_dir(directory).expect("read file icon source directory") {
        let path = entry.expect("read source directory entry").path();
        if path.extension().and_then(|value| value.to_str()) != Some("svg") {
            continue;
        }
        let name = path
            .file_stem()
            .and_then(|value| value.to_str())
            .expect("UTF-8 SVG file name")
            .to_owned();
        let svg = fs::read_to_string(&path)
            .unwrap_or_else(|error| panic!("read {}: {error}", path.display()));
        let (width, height) = view_box(&svg, &path);
        let styles = style_colors(&svg);
        let triangles = tessellate_svg(&svg, &styles, &path);
        let variant = variant_name(set, &name);
        let constant = format!("FILE_ICON_{}", constant_name(&variant));
        assets.push(Asset {
            set: set.to_owned(),
            name,
            variant,
            constant,
            width,
            height,
            triangles,
        });
    }
    assets
}

fn view_box(svg: &str, path: &Path) -> (f64, f64) {
    let value = attribute(svg, "viewBox")
        .unwrap_or_else(|| panic!("missing viewBox in {}", path.display()));
    let values: Vec<f64> = value
        .split_whitespace()
        .map(|part| part.parse().expect("numeric viewBox value"))
        .collect();
    assert!(values.len() == 4, "invalid viewBox in {}", path.display());
    (values[2], values[3])
}

fn style_colors(svg: &str) -> BTreeMap<String, u32> {
    let mut colors = BTreeMap::new();
    let mut rest = svg;
    while let Some(start) = rest.find('.') {
        rest = &rest[start + 1..];
        let Some(open) = rest.find('{') else { break };
        let class = rest[..open].trim();
        let Some(close) = rest[open + 1..].find('}') else {
            break;
        };
        let rules = &rest[open + 1..open + 1 + close];
        if let Some(fill) = rules
            .split(';')
            .find_map(|rule| rule.trim().strip_prefix("fill:"))
        {
            if let Some(color) = parse_color(fill.trim()) {
                colors.insert(class.to_owned(), color);
            }
        }
        rest = &rest[open + 1 + close + 1..];
    }
    colors
}

fn tessellate_svg(svg: &str, styles: &BTreeMap<String, u32>, path: &Path) -> Vec<Triangle> {
    let mut triangles = Vec::new();
    let mut rest = svg;
    while let Some(start) = rest.find("<path") {
        rest = &rest[start + 5..];
        let end = rest.find('>').expect("terminated path element");
        let element = &rest[..end];
        let data = attribute(element, "d")
            .unwrap_or_else(|| panic!("path without d in {}", path.display()));
        let class_color = attribute(element, "class").and_then(|class| styles.get(class).copied());
        let fill = match attribute(element, "fill") {
            Some("none") => 0x00000000,
            Some(value) => parse_color(value).or(class_color).unwrap_or(0xff000000),
            None => class_color.unwrap_or(0xff000000),
        };
        let commands = normalize(PathParser::from(data).map(|segment| {
            segment.unwrap_or_else(|error| panic!("parse path in {}: {error}", path.display()))
        }));
        let lyon_path = lyon_path(&commands);

        if fill != 0x00000000 {
            let mut geometry: VertexBuffers<lyon_tessellation::math::Point, u16> =
                VertexBuffers::new();
            FillTessellator::new()
                .tessellate_path(
                    &lyon_path,
                    &FillOptions::default(),
                    &mut BuffersBuilder::new(&mut geometry, |vertex: FillVertex| vertex.position()),
                )
                .unwrap_or_else(|error| {
                    panic!("fill tessellation failed in {}: {error}", path.display())
                });
            append_triangles(&mut triangles, &geometry, fill);
        }

        if let Some(stroke) = attribute(element, "stroke").and_then(parse_color) {
            let width = attribute(element, "stroke-width")
                .and_then(|value| value.parse::<f32>().ok())
                .unwrap_or(1.0);
            let mut geometry: VertexBuffers<lyon_tessellation::math::Point, u16> =
                VertexBuffers::new();
            StrokeTessellator::new()
                .tessellate_path(
                    &lyon_path,
                    &StrokeOptions::default().with_line_width(width),
                    &mut BuffersBuilder::new(&mut geometry, |vertex: StrokeVertex| {
                        vertex.position()
                    }),
                )
                .unwrap_or_else(|error| {
                    panic!("stroke tessellation failed in {}: {error}", path.display())
                });
            append_triangles(&mut triangles, &geometry, stroke);
        }
        rest = &rest[end + 1..];
    }
    assert!(
        !triangles.is_empty(),
        "SVG contains no drawable paths: {}",
        path.display()
    );
    triangles
}

fn append_triangles(
    destination: &mut Vec<Triangle>,
    geometry: &VertexBuffers<lyon_tessellation::math::Point, u16>,
    color: u32,
) {
    for indices in geometry.indices.chunks_exact(3) {
        let a = geometry.vertices[usize::from(indices[0])];
        let b = geometry.vertices[usize::from(indices[1])];
        let c = geometry.vertices[usize::from(indices[2])];
        destination.push(Triangle {
            a: [a.x, a.y],
            b: [b.x, b.y],
            c: [c.x, c.y],
            color,
        });
    }
}

fn lyon_path(commands: &[Command]) -> LyonPath {
    let mut builder = LyonPath::builder();
    let mut open = false;
    for command in commands {
        match *command {
            Command::Move(x, y) => {
                if open {
                    builder.end(false);
                }
                builder.begin(lyon_tessellation::math::point(x as f32, y as f32));
                open = true;
            }
            Command::Line(x, y) => {
                builder.line_to(lyon_tessellation::math::point(x as f32, y as f32));
            }
            Command::Quad(x1, y1, x, y) => {
                builder.quadratic_bezier_to(
                    lyon_tessellation::math::point(x1 as f32, y1 as f32),
                    lyon_tessellation::math::point(x as f32, y as f32),
                );
            }
            Command::Cubic(x1, y1, x2, y2, x, y) => {
                builder.cubic_bezier_to(
                    lyon_tessellation::math::point(x1 as f32, y1 as f32),
                    lyon_tessellation::math::point(x2 as f32, y2 as f32),
                    lyon_tessellation::math::point(x as f32, y as f32),
                );
            }
            Command::Close => {
                builder.close();
                open = false;
            }
        }
    }
    if open {
        builder.end(false);
    }
    builder.build()
}

fn attribute<'a>(source: &'a str, name: &str) -> Option<&'a str> {
    let prefix = format!("{name}=\"");
    let mut offset = 0;
    while let Some(found) = source[offset..].find(&prefix) {
        let start = offset + found;
        if start == 0 || source.as_bytes()[start - 1].is_ascii_whitespace() {
            let value_start = start + prefix.len();
            let end = source[value_start..].find('\"')?;
            return Some(&source[value_start..value_start + end]);
        }
        offset = start + prefix.len();
    }
    None
}

fn parse_color(value: &str) -> Option<u32> {
    let value = value.trim();
    let hex = value.strip_prefix('#')?;
    let digits = match hex.len() {
        3 => {
            let mut expanded = String::with_capacity(6);
            for character in hex.chars() {
                expanded.push(character);
                expanded.push(character);
            }
            expanded
        }
        6 => hex.to_owned(),
        8 => hex[..6].to_owned(),
        _ => return None,
    };
    let rgb = u32::from_str_radix(&digits, 16).ok()?;
    Some((rgb << 8) | 0xff)
}

fn variant_name(set: &str, name: &str) -> String {
    let mut output = set.to_owned();
    let mut uppercase_next = true;
    for character in name.chars() {
        if !character.is_ascii_alphanumeric() {
            uppercase_next = true;
            continue;
        }
        if uppercase_next {
            output.push(character.to_ascii_uppercase());
            uppercase_next = false;
        } else {
            output.push(character);
        }
    }
    if output
        .chars()
        .nth(set.len())
        .is_some_and(|character| character.is_ascii_digit())
    {
        output.insert(set.len(), 'X');
    }
    output
}

fn constant_name(variant: &str) -> String {
    let mut output = String::new();
    for (index, character) in variant.chars().enumerate() {
        if index > 0 && character.is_ascii_uppercase() {
            output.push('_');
        }
        output.push(character.to_ascii_uppercase());
    }
    output
}

fn normalize(segments: impl Iterator<Item = PathSegment>) -> Vec<Command> {
    let mut commands = Vec::new();
    let mut current = (0.0, 0.0);
    let mut subpath_start = current;
    let mut cubic_control = None;
    let mut quadratic_control = None;
    for segment in segments {
        let endpoint = |abs: bool, x: f64, y: f64, current: (f64, f64)| {
            if abs {
                (x, y)
            } else {
                (current.0 + x, current.1 + y)
            }
        };
        match segment {
            PathSegment::MoveTo { abs, x, y } => {
                current = endpoint(abs, x, y, current);
                subpath_start = current;
                commands.push(Command::Move(current.0, current.1));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::LineTo { abs, x, y } => {
                current = endpoint(abs, x, y, current);
                commands.push(Command::Line(current.0, current.1));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::HorizontalLineTo { abs, x } => {
                current.0 = if abs { x } else { current.0 + x };
                commands.push(Command::Line(current.0, current.1));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::VerticalLineTo { abs, y } => {
                current.1 = if abs { y } else { current.1 + y };
                commands.push(Command::Line(current.0, current.1));
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::CurveTo {
                abs,
                x1,
                y1,
                x2,
                y2,
                x,
                y,
            } => {
                let first = endpoint(abs, x1, y1, current);
                let second = endpoint(abs, x2, y2, current);
                current = endpoint(abs, x, y, current);
                commands.push(Command::Cubic(
                    first.0, first.1, second.0, second.1, current.0, current.1,
                ));
                cubic_control = Some(second);
                quadratic_control = None;
            }
            PathSegment::SmoothCurveTo { abs, x2, y2, x, y } => {
                let first = cubic_control
                    .map(|control| (current.0 * 2.0 - control.0, current.1 * 2.0 - control.1))
                    .unwrap_or(current);
                let second = endpoint(abs, x2, y2, current);
                current = endpoint(abs, x, y, current);
                commands.push(Command::Cubic(
                    first.0, first.1, second.0, second.1, current.0, current.1,
                ));
                cubic_control = Some(second);
                quadratic_control = None;
            }
            PathSegment::Quadratic { abs, x1, y1, x, y } => {
                let control = endpoint(abs, x1, y1, current);
                current = endpoint(abs, x, y, current);
                commands.push(Command::Quad(control.0, control.1, current.0, current.1));
                quadratic_control = Some(control);
                cubic_control = None;
            }
            PathSegment::SmoothQuadratic { abs, x, y } => {
                let control = quadratic_control
                    .map(|previous| (current.0 * 2.0 - previous.0, current.1 * 2.0 - previous.1))
                    .unwrap_or(current);
                current = endpoint(abs, x, y, current);
                commands.push(Command::Quad(control.0, control.1, current.0, current.1));
                quadratic_control = Some(control);
                cubic_control = None;
            }
            PathSegment::EllipticalArc {
                abs,
                rx,
                ry,
                x_axis_rotation,
                large_arc,
                sweep,
                x,
                y,
            } => {
                let start = current;
                current = endpoint(abs, x, y, current);
                append_arc(
                    &mut commands,
                    start,
                    current,
                    rx,
                    ry,
                    x_axis_rotation,
                    large_arc,
                    sweep,
                );
                cubic_control = None;
                quadratic_control = None;
            }
            PathSegment::ClosePath { .. } => {
                current = subpath_start;
                commands.push(Command::Close);
                cubic_control = None;
                quadratic_control = None;
            }
        }
    }
    commands
}

fn append_arc(
    commands: &mut Vec<Command>,
    start: (f64, f64),
    end: (f64, f64),
    radius_x: f64,
    radius_y: f64,
    rotation: f64,
    large_arc: bool,
    sweep: bool,
) {
    let mut radius_x = radius_x.abs();
    let mut radius_y = radius_y.abs();
    if radius_x <= f64::EPSILON || radius_y <= f64::EPSILON || start == end {
        commands.push(Command::Line(end.0, end.1));
        return;
    }

    let phi = rotation.to_radians();
    let cosine = phi.cos();
    let sine = phi.sin();
    let half_x = (start.0 - end.0) * 0.5;
    let half_y = (start.1 - end.1) * 0.5;
    let transformed_x = cosine * half_x + sine * half_y;
    let transformed_y = -sine * half_x + cosine * half_y;
    let lambda = transformed_x * transformed_x / (radius_x * radius_x)
        + transformed_y * transformed_y / (radius_y * radius_y);
    if lambda > 1.0 {
        let scale = lambda.sqrt();
        radius_x *= scale;
        radius_y *= scale;
    }

    let numerator = (radius_x * radius_x * radius_y * radius_y
        - radius_x * radius_x * transformed_y * transformed_y
        - radius_y * radius_y * transformed_x * transformed_x)
        .max(0.0);
    let denominator = radius_x * radius_x * transformed_y * transformed_y
        + radius_y * radius_y * transformed_x * transformed_x;
    let sign = if large_arc == sweep { -1.0 } else { 1.0 };
    let factor = if denominator <= f64::EPSILON {
        0.0
    } else {
        sign * (numerator / denominator).sqrt()
    };
    let center_transformed_x = factor * radius_x * transformed_y / radius_y;
    let center_transformed_y = factor * -radius_y * transformed_x / radius_x;
    let center = (
        cosine * center_transformed_x - sine * center_transformed_y + (start.0 + end.0) * 0.5,
        sine * center_transformed_x + cosine * center_transformed_y + (start.1 + end.1) * 0.5,
    );
    let start_vector = (
        (transformed_x - center_transformed_x) / radius_x,
        (transformed_y - center_transformed_y) / radius_y,
    );
    let end_vector = (
        (-transformed_x - center_transformed_x) / radius_x,
        (-transformed_y - center_transformed_y) / radius_y,
    );
    let angle = |left: (f64, f64), right: (f64, f64)| {
        (left.0 * right.1 - left.1 * right.0).atan2(left.0 * right.0 + left.1 * right.1)
    };
    let start_angle = angle((1.0, 0.0), start_vector);
    let mut sweep_angle = angle(start_vector, end_vector);
    if !sweep && sweep_angle > 0.0 {
        sweep_angle -= std::f64::consts::TAU;
    } else if sweep && sweep_angle < 0.0 {
        sweep_angle += std::f64::consts::TAU;
    }
    let steps = (sweep_angle.abs() * radius_x.max(radius_y))
        .ceil()
        .clamp(8.0, 96.0) as usize;
    for step in 1..=steps {
        let current_angle = start_angle + sweep_angle * step as f64 / steps as f64;
        let arc_x = radius_x * current_angle.cos();
        let arc_y = radius_y * current_angle.sin();
        commands.push(Command::Line(
            center.0 + cosine * arc_x - sine * arc_y,
            center.1 + sine * arc_x + cosine * arc_y,
        ));
    }
}
